In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

<img src="https://i.imgur.com/HPVTZpJ.png" width=900>

#### Classic Python/NumPy Comparison - Why NumPy?

In [2]:
from numpy import * 
import time
def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

trad_version()

1.6897127628326416

In [3]:
def numpy_version():
    t1 = time.time()
    X = arange(10000000)
    Y = arange(10000000)
    Z = X + Y
    return time.time() - t1

numpy_version()

0.02934551239013672

In [4]:
result = trad_version() / numpy_version()

In [7]:
print(f"NumPy is {result} times faster than Python.")

NumPy is 60.16956982506418 times faster than Python.


---

In [10]:
import numpy as np

In [9]:
# Creating a NumPy array from a Python list
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [14]:
# Convert the list to a NumPy array
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [34]:
# Display the type, data type, and data buffer of the NumPy array arr1
type(arr1), arr1.dtype, arr1.data

(numpy.ndarray, dtype('int32'), <memory at 0x000001CD1B31C040>)

In [17]:
# Converts integer elements in 'arr1' to floats.
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [35]:
# Create a one-dimensional NumPy array with values ranging from 0 to 9
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Create a one-dimensional NumPy array with values ranging from 0 to 90 with a step size of 10
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
# Create a one-dimensional NumPy array with values ranging from 100 to 10 with a step size of -10
np.arange(100, 0, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [31]:
# Create a NumPy array with values ranging from 0 to 9
arr2 = np.arange(10)
# Display the shape of the NumPy array
arr2.shape

(10,)

In [32]:
# Display the number of bytes consumed by the array
arr2.nbytes

40

In [33]:
# Display the length of the NumPy array
len(arr2)

10

In [42]:
# Create a one-dimensional NumPy array of zeros with length 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
# Create a one-dimensional NumPy array of ones with length 10
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
# Create a one-dimensional NumPy array by repeating the value 10 five times
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [45]:
# Create a NumPy array 'a' with values [10, 20, 30]
a = np.array([10, 20, 30])
# Repeat each element in the array 'a' three times
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [47]:
# Create a one-dimensional NumPy array of length 5 filled with the value 10
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [49]:
arr3 = np.arange(1, 20)
# Select elements from the array where the value is odd (using boolean indexing)
arr3[arr3 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [51]:
# Select elements from the array where the value is even (using boolean indexing)
arr3[arr3 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
# Create a one-dimensional NumPy array with 4 evenly spaced values from 10 to 20 (inclusive)
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [55]:
# Create a one-dimensional NumPy array with 10 evenly spaced values from 10 to 20 (inclusive)
np.linspace(10, 20, 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

* The **first random expression** is a module. The **second random expression** is a function inside that module.

In [58]:
# Creating a random number
# Generate a one-dimensional NumPy array with 4 random values between 0 and 1
np.random.random(4)

array([0.45092456, 0.09574525, 0.90677531, 0.38306818])

In [60]:
# Generate a one-dimensional NumPy array with 5 random integers between 0 (inclusive) and 500 (exclusive)
np.random.randint(0, 500, 5)

array([ 60, 357,  67,  33, 297])

In [66]:
# Seed
# Set a seed for reproducibility
np.random.seed(123)
# Generate a one-dimensional NumPy array with 10 random integers between 0 (inclusive) and 100 (exclusive)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [67]:
# Generate a one-dimensional NumPy array with 10 random integers between 0 (inclusive) and 100 (exclusive)
np.random.randint(0, 100, 10)

array([73, 32, 46, 96, 25, 83, 78, 36, 96, 80])

In [68]:
np.random.seed(123)
# Generate a one-dimensional NumPy array with 10 random integers between 0 (inclusive) and 100 (exclusive)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [69]:
# Set a seed for reproducibility
np.random.seed(101)
# Generate a one-dimensional NumPy array with 10 random integers between 0 (inclusive) and 100 (exclusive)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [71]:
# Generate a one-dimensional NumPy array with 10 random values drawn from a uniform distribution between 5 and 10
f1 = np.random.uniform(5, 10, size=10)
f1

array([5.41780717, 8.01774211, 8.64496379, 6.38119414, 8.42653164,
       7.58933737, 5.24242269, 5.68934619, 5.93483713, 9.97158951])

In [73]:
# Apply the floor function to round down each element in the array to the nearest integer
np.floor(f1)

array([5., 8., 8., 6., 8., 7., 5., 5., 5., 9.])

In [76]:
# Apply the truncation function to remove the decimal part of each element in the array
np.trunc(f1)

array([5., 8., 8., 6., 8., 7., 5., 5., 5., 9.])

In [78]:
# Convert the data type of the NumPy array f1 to integer, effectively truncating the decimal part
f1.astype(int)

array([5, 8, 8, 6, 8, 7, 5, 5, 5, 9])

In [80]:
# Generate a one-dimensional NumPy array with 10 random values drawn from a standard normal distribution (mean=0, std=1)
f2 = np.random.randn(10)
f2

array([ 0.80770591,  0.07295968,  0.63878701,  0.3296463 , -0.49710402,
       -0.7540697 , -0.9434064 ,  0.48475165, -0.11677332,  1.9017548 ])

In [84]:
# Enumeration
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


### Operations on the arrays

In [87]:
arr3 = np.arange(1, 20)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [101]:
# Calculate the sum of all elements in the NumPy array arr3
arr3.sum()

190

In [102]:
# Calculate the cumulative sum of elements in the NumPy array arr3
np.cumsum(arr3)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

In [103]:
# Find the minimum value in the NumPy array arr3
arr3.min()

1

In [104]:
# Find the maximum value in the NumPy array arr3
arr3.max()

19

In [105]:
# Find the index of the minimum value in the NumPy array arr3
arr3.argmin()

0

In [106]:
# Find the index of the maximum value in the NumPy array arr3
arr3.argmax()

18

In [107]:
# Calculate the mean (average) of elements in the NumPy array arr3
arr3.mean()

10.0

In [108]:
# Calculate the median of elements in the NumPy array arr3
np.median(arr3)

10.0

In [109]:
# Calculate the variance of elements in the NumPy array arr3
arr3.var()

30.0

In [110]:
# Calculate the standard deviation of elements in the NumPy array arr3
np.std(arr3)

5.477225575051661

### 2D Arrays

**0D** ---> Point

**1D** ---> Vector

**2D** ---> Matrix

**\>=3D** ---> Tensor, Matrix

In [111]:
A = np.array([[1, 2, 3, 0],
              [5, 6, 7, 22],
              [10, 11, 1, 13],
              [14, 15, 16, 3]])

A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [112]:
A.sum()

129

In [113]:
A.max()

22

In [114]:
A.min()

0

In [115]:
A.cumsum()

array([  1,   3,   6,   6,  11,  17,  24,  46,  56,  67,  68,  81,  95,
       110, 126, 129])

In [116]:
A.argmin()

3

In [117]:
A.argmax()

7

In [118]:
A.mean()

8.0625

In [120]:
np.median(A)

6.5

In [121]:
A.var()

40.30859375

In [122]:
np.std(A)

6.348904925260734

<img src="https://www.sharpsightlabs.com/wp-content/uploads/2018/12/numpy-arrays-have-axes_updated_v2.png" width=500>

In [125]:
# Column-based minimum value
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [126]:
# Row-based minimum value
np.amin(A, axis=1)

array([0, 5, 1, 3])

In [127]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


### Element replacement / conversion

In [129]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [136]:
# Use np.where to replace even elements with 0 and keep odd elements unchanged
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [131]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [137]:
# Use np.where to replace occurrences of the value 10 with 99 in the NumPy array ar2
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [133]:
ar3 = np.arange(0, 100, 10)
ar3

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [138]:
# Use np.put to replace specific elements at indices 0, 3, and 5 with values 33, 55, and 99 respectively
np.put(ar3, [0, 3, 5], [33, 55, 99])
ar3

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

### Dealing with missing values

In [140]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [144]:
# Use np.isnan to check for NaN values in the array 'a'
np.isnan(a)

array([False, False, False, False, False, False, False, False])

In [145]:
# Use np.where to get the indices of NaN values in 'a'
np.where(np.isnan(a))

(array([], dtype=int64),)

In [146]:
# Replace NaN values in 'a' with a specific value, in this case, replace NaN with 99
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [148]:
# Check if there are any NaN values in the array 'a' using np.isnan
np.isnan(a).any()

False

In [149]:
A = np.array([[1, 2, np.nan, 4],
              [np.nan, 6, 7, 8],
              [10, np.nan, 12, 13],
              [14, 15, 16, 17]])

A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [150]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [151]:
np.isnan(A).any()

True

In [152]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))